name: spenzy_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  grpc: ^3.2.4
  protobuf: ^3.1.0
  fixnum: ^1.1.0
  flutter_secure_storage: ^9.0.0
  file_picker:
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker.git
      ref: 36425c

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true 